- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  changed_when: false
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
- name: Install Python libraries
  become: true
  ansible.builtin.pip:
    name:
      - botocore
      - boto3
