---
- name: App
  hosts: all
  roles:
    - common
    - pufferfish
    - role: cloudwatch
      vars:
        log_files:
          - file_path: /var/log/pufferfish/stdout.log
            log_group_name: pufferfish/app
            log_stream_name: "{instance_id}"
          - file_path: /var/log/pufferfish/stderr.log
            log_group_name: pufferfish/app
            log_stream_name: "{instance_id}"
