---
- name: Terraform Backend
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: eu-west-1
    tfbackend_s3_name_parameter_path: "/pufferfish/infra/tfbackend_s3_name"
    _tfbackend_s3_name: "{{ lookup('aws_ssm', tfbackend_s3_name_parameter_path, on_missing='skip') }}"
  tasks:
    - name: Create the S3 name parameter
      when: _tfbackend_s3_name == ''
      community.aws.ssm_parameter:
        name: "{{ tfbackend_s3_name_parameter_path }}"
        description: Managed by Ansible
        value: pufferfish-tfstate-{{ lookup('community.general.random_string', upper=false, special=false) }}
    - name: Create the S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ lookup('aws_ssm', tfbackend_s3_name_parameter_path) }}"
        versioning: true
        encryption: "aws:kms"
        public_access:
          block_public_acls: true
          block_public_policy: true
          ignore_public_acls: true
          restrict_public_buckets: true
        tags:
          ManagedBy: Ansible
    - name: Create the DynamoDB table for locking
      community.aws.dynamodb_table:
        name: "{{ lookup('aws_ssm', tfbackend_s3_name_parameter_path) }}-locks"
        region: "{{ aws_region }}"
        billing_mode: PAY_PER_REQUEST
        hash_key_name: LockID
        hash_key_type: STRING
        tags:
          ManagedBy: Ansible
