---
pufferfish_app_params: >-
  {{
    lookup(
      'aws_ssm',
      '/pufferfish/app',
      recursive=true,
      bypath=true,
      shortnames=true
    )
  }}
pufferfish_binary_path: /usr/local/bin/pufferfish
pufferfish_builds_s3_name: "{{ lookup('aws_ssm', '/pufferfish/infra/builds_s3_name') }}"
pufferfish_user_name: pufferfish
